table Feuil1
	lineageTag: 1aa5b3c0-698d-423c-bf23-0a062e07bdee

	column Name
		dataType: string
		lineageTag: bf05f8c8-4e07-41d6-aaf2-f946e7175df3
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column URL
		dataType: string
		lineageTag: 89312dee-5e64-40f9-a788-dfc1ce122649
		summarizeBy: none
		sourceColumn: URL

		annotation SummarizationSetBy = Automatic

	partition Feuil1 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\LENOVO\Downloads\dashbord PI.xlsx"), null, true),
				    Feuil1_Sheet = Source{[Item="Feuil1",Kind="Sheet"]}[Data],
				    #"Type modifié" = Table.TransformColumnTypes(Feuil1_Sheet,{{"Column1", type text}, {"Column2", type text}}),
				    #"En-têtes promus" = Table.PromoteHeaders(#"Type modifié", [PromoteAllScalars=true]),
				    #"Type modifié1" = Table.TransformColumnTypes(#"En-têtes promus",{{"Name", type text}, {"URL", type text}})
				in
				    #"Type modifié1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

