table User
	lineageTag: 3744256c-bfa4-46e8-a02f-d2c9e3187b5d

	column User
		dataType: string
		lineageTag: a5c8cb5c-8bbb-445c-8323-0532533c6bd7
		summarizeBy: none
		sourceColumn: User

		annotation SummarizationSetBy = Automatic

	column Page
		dataType: string
		lineageTag: acc16400-50f1-490a-aa8e-3ef1f19a1ea5
		summarizeBy: none
		sourceColumn: Page

		annotation SummarizationSetBy = Automatic

	partition User = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45Wyk0sSszVy8hJzMl0SC0uKMos0SvJU9JRcs0tyMmvTEzKzMksObxSKVYnWqk4sagoUS8xKSk1D0WpY0puZnFxZn6eUmwsAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [User = _t, Page = _t]),
				    #"Type modifié" = Table.TransformColumnTypes(Source,{{"User", type text}, {"Page", type text}}),
				    #"Valeur remplacée" = Table.ReplaceValue(#"Type modifié","maram.hlali@esprit.tn","maram.HLALI@esprit.tn",Replacer.ReplaceText,{"User"}),
				    #"Valeur remplacée1" = Table.ReplaceValue(#"Valeur remplacée","maram.HLALI@esprit.tn","rania.felah@esprit.tn",Replacer.ReplaceText,{"User"})
				in
				    #"Valeur remplacée1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

